### ISSUE TITLE
Link to the publication

### ISSUE THREAD

**Issue by mhwadsworth91** [regeneron-mpds/ICON#1]
Hello, I have enjoyed using this tool, however, I am having difficulty finding the publication provided in the ReadMe (Zhang et al. 2021). At your earliest convenience, could you please provide the DOI link?

Thank you.

**Comment by regeneron-mpds** [comment]
Hello Marc,

Please see this link and these references:
https://advances.sciencemag.org/content/7/20/eabf5835.abstract

Science Advances  14 May 2021:
Vol. 7, no. 20, eabf5835
DOI: 10.1126/sciadv.abf5835

Thanks,
Christian
--

From: Marc Wadsworth ***@***.***>
Date: Wednesday, June 9, 2021 at 9:17 AM
To: regeneron-mpds/ICON ***@***.***>
Cc: Subscribed ***@***.***>
Subject: <External> [regeneron-mpds/ICON] Link to the publication (#1)

EXTERNAL MESSAGE
________________________________


Hello, I have enjoyed using this tool, however, I am having difficulty finding the publication provided in the ReadMe (Zhang et al. 2021). At your earliest convenience, could you please provide the DOI link?

Thank you.
